### ISSUE TITLE
Could not load content for chrome-extension

### ISSUE THREAD

**Issue by khasanka** [djipco/chrome-apps-serialport#1]
I am using chrome-apps-serialport with nwjs in windows 10 OS. I am showing this message in chrome console 

DevTools failed to load SourceMap: Could not load content for chrome-extension://cfkggdecgdmblbpgpmegjhkaeocljjae/chrome-apps-serialport.min.js.map: System error: net::ERR_FILE_NOT_FOUND

**Comment by djipco** [comment]
Thanks for reporting this. However, there's not much I can do since this is a [known bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1053535) in Chrome. A [patch](https://chromium-review.googlesource.com/c/chromium/src/+/2141899) has been coded but has not been deployed yet.

Basically, it is not currently possible to load a source-map from the `chrome-extension://` protocol (which is what is used by NW.js).
